name = "CoaxialAutogyroStacking"
uuid = "cb2a5e45-b910-4a0e-9959-8ee2b2784885"
version = "0.1.0"
authors = ["Rod Read <rod@windswept.energy>"]

[deps]

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
