#!/usr/bin/env python3
"""regenerate_all.py — regenerate sweep and all dependent diagrams.

Run after any change to the physics solvers (polygon_line.jl, bem.jl, stack.jl).
Re-runs the sweep, then re-runs every diagram script, then reports which
diagrams changed significantly and need HITL re-review.

Usage:
    .venv-charts/bin/python3 regenerate_all.py
"""
import subprocess, sys, os, csv, shutil, statistics
from pathlib import Path
from collections import defaultdict

REPO = Path(__file__).resolve().parent
VENV_PYTHON = str(REPO / ".venv-charts" / "bin" / "python3")
SWEEP_SCRIPT = REPO / "scripts" / "bem_full_sweep.jl"
SWEEP_OUTPUT = REPO / "bem_full_sweep.tsv"

# ── Helpers ─────────────────────────────────────────────────────────────────

def run_cmd(cmd, cwd, timeout=120, label=""):
    """Run a command, print result, return success bool."""
    result = subprocess.run(cmd, capture_output=True, text=True,
                           cwd=str(cwd), timeout=timeout)
    status = "\u2713" if result.returncode == 0 else "\u2717"
    out = result.stdout.strip().split("\n")[0] if result.stdout else ""
    print(f"  {status} {label}: {out}" if label else f"  {status} {out}")
    if result.returncode != 0:
        print(f"    ERROR: {result.stderr[:300]}")
    return result.returncode == 0

def run_python(script, cwd, label=""):
    """Run a Python diagram script."""
    return run_cmd([VENV_PYTHON, script], cwd, timeout=60, label=label)

def run_julia(script, cwd, label=""):
    """Run a Julia script."""
    return run_cmd(["julia", f"--project={REPO}", script], cwd,
                   timeout=120, label=label)

def load_tension_summary(tsv_path):
    """Load mean anchor tension per (radius, n_rotors, profile)."""
    cells = defaultdict(list)
    with open(tsv_path) as f:
        for row in csv.DictReader(f, delimiter="\t"):
            t = float(row["anchor_tension"])
            if t > 0:
                cells[(float(row["radius"]), int(row["n_rotors"]),
                       row["profile"])].append(t)
    return {k: statistics.mean(v) for k, v in cells.items() if v}

# ── Step 1: BEM Sweep ──────────────────────────────────────────────────────
print("=" * 60)
print("Step 1: Regenerating BEM sweep...")
if not run_julia(str(SWEEP_SCRIPT.name), str(SWEEP_SCRIPT.parent),
                 "BEM sweep"):
    print("FATAL: Sweep failed")
    sys.exit(1)

# ── Step 2: Compare with previous ──────────────────────────────────────────
prev_path = REPO / "bem_full_sweep_prev.tsv"
prev_tensions = load_tension_summary(str(prev_path)) if prev_path.exists() else {}
new_tensions = load_tension_summary(str(SWEEP_OUTPUT))
diffs = []
if prev_tensions:
    for k, new_t in new_tensions.items():
        old_t = prev_tensions.get(k)
        if old_t and old_t > 0:
            pct = (new_t - old_t) / old_t * 100
            if abs(pct) > 2:
                diffs.append((k, old_t, new_t, pct))
    if diffs:
        print(f"\n  {len(diffs)} configurations changed >2%:")
        for k, old, new, pct in sorted(diffs, key=lambda x: abs(x[3]),
                                       reverse=True)[:10]:
            print(f"    R={k[0]} N={k[1]} {k[2]}: {old:.0f} \u2192 {new:.0f} N ({pct:+.1f}%)")

shutil.copy(str(SWEEP_OUTPUT), str(prev_path))

# ── Step 3: Julia-dependent data generation ────────────────────────────────
print(f"\n{'='*60}")
print("Step 3: Julia data generation...")

julia_diagrams = [
    ("diagrams/bem-tension-accum", ["compute_tension_profile.jl",
                                     "compute_tension_profile_v2.jl"]),
    ("diagrams/bem-radial-loading", ["compute_radial_loading.jl"]),
    ("diagrams/bem-force-breakdown", ["compute_force_breakdown.jl"]),
]

for d, scripts in julia_diagrams:
    for s in scripts:
        run_julia(s, str(REPO / d), f"{d}/{s}")

# Also regenerate comparison sweep data
run_julia("gen_comparison_sweep.jl", str(REPO / "scripts"),
          "Snel + solver comparison sweep")

# ── Step 4: All Python diagram scripts ─────────────────────────────────────
print(f"\n{'='*60}")
print("Step 4: Regenerating all diagram PNGs...")

# All diagram directories with .py scripts
diagram_dirs = sorted(
    d for d in (REPO / "diagrams").iterdir()
    if d.is_dir() and (d / f"{d.name}.py").exists()
)

ok = fail = 0
for d in diagram_dirs:
    script = f"{d.name}.py"
    success = run_python(script, str(d), f"{d.name}")
    if success:
        ok += 1
    else:
        fail += 1

# Handle sweep-profile-cv (generated by sweep-profile-nkg)
cv_d = REPO / "diagrams" / "sweep-profile-cv"
cv_png = REPO / "diagrams" / "sweep-profile-nkg" / "sweep-profile-cv.png"
if cv_png.exists() and cv_d.exists():
    shutil.copy(str(cv_png), str(cv_d / "sweep-profile-cv.png"))

# Handle sweep-profile-nkg dual output copy to sweep-profile-cv
nkg_cv_png = REPO / "diagrams" / "sweep-profile-nkg" / "sweep-profile-cv.png"
cv_target = REPO / "diagrams" / "sweep-profile-cv" / "sweep-profile-cv.png"
if nkg_cv_png.exists():
    cv_target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy(str(nkg_cv_png), str(cv_target))

# ── Step 5: PCA-2 sweep (for comparison charts) ────────────────────────────
print(f"\n{'='*60}")
print("Step 5: PCA-2 comparison sweep...")
run_julia("gen_pca2_sweep.jl", str(REPO / "scripts"), "PCA-2 sweep")

# Regenerate PCA-2-dependent charts
for d_name in ["bem-pca2-vs-bem", "sweep-pareto-mass", "sweep-pareto-cv",
               "sweep-tension-vs-wind", "sweep-heatmap"]:
    d = REPO / "diagrams" / d_name
    if (d / f"{d_name}.py").exists():
        run_python(f"{d_name}.py", str(d), d_name)

# ── Summary ────────────────────────────────────────────────────────────────
print(f"\n{'='*60}")
print(f"Regeneration complete.")
print(f"Python diagrams: {ok} OK, {fail} failed")
print(f"Sweep: {SWEEP_OUTPUT} ({SWEEP_OUTPUT.stat().st_size} bytes)")

if prev_tensions and diffs:
    print(f"\n\u26a0 {len(diffs)} configurations shifted >2%. Diagrams need re-review.")
    print("Run ste-lint.py on updated captions before HITL rounds.")
else:
    print("No significant changes — diagrams should be current.")
